# House Price Prediction with Categorical Data

## Objective

This project predicts house prices based on area and town using Linear Regression.

Two methods are compared:
- Dummy variables with Pandas
- One-Hot Encoding with Scikit-learn

In [3]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

## 1. Load the Dataset

In [4]:
df = pd.read_csv('homepricessss.csv')
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

## 2. Dummy Variables with Pandas

In [5]:
dummies = pd.get_dummies(df["town"], dtype=int)
dummies

    monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [6]:
merged = pd.concat([df, dummies], axis="columns")
merged

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [7]:
final = merged.drop(["town"], axis="columns")
final

    area   price  monroe township  robinsville  west windsor
0   2600  550000                1            0             0
1   3000  565000                1            0             0
2   3200  610000                1            0             0
3   3600  680000                1            0             0
4   4000  725000                1            0             0
5   2600  585000                0            0             1
6   2800  615000                0            0             1
7   3300  650000                0            0             1
8   3600  710000                0            0             1
9   2600  575000                0            1             0
10  2900  600000                0            1             0
11  3100  620000                0            1             0
12  3600  695000                0            1             0

In [8]:
final = final.drop(['west windsor'], axis='columns')
final

    area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [13]:
#X = final.drop('price', axis='columns')
X = final[['area','monroe township','robinsville']]
X

    area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [14]:
y=final.price

In [15]:

model = LinearRegression()

In [16]:
model.fit(X,y)

LinearRegression()

In [18]:
model.coef_

array([   126.89744141, -40013.97548914, -14327.56396474])

In [19]:
model.intercept_

np.float64(249790.36766292516)

In [20]:
model.predict(X)

array([539709.7398409 , 590468.71640508, 615848.20468716, 666607.18125134,
       717366.15781551, 579723.71533005, 605103.20361213, 668551.92431735,
       706621.15674048, 565396.15136531, 603465.38378844, 628844.87207052,
       692293.59277574])

In [21]:
model.score(X,y)

0.9573929037221874

In [23]:
new_house = pd.DataFrame({
    "area": [3400],
    "monroe township": [0],
    "robinsville": [0]
})

model.predict(new_house)

array([681241.66845839])

## 3. One-Hot Encoding with Scikit-learn

In [26]:
X_ohe = df[["town", "area"]].copy()
X_ohe

               town  area
0   monroe township  2600
1   monroe township  3000
2   monroe township  3200
3   monroe township  3600
4   monroe township  4000
5      west windsor  2600
6      west windsor  2800
7      west windsor  3300
8      west windsor  3600
9       robinsville  2600
10      robinsville  2900
11      robinsville  3100
12      robinsville  3600

In [28]:
y = df["price"]
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [37]:
ct = ColumnTransformer(transformers=[("town",OneHotEncoder(drop="first"),["town"])],remainder="passthrough")

In [42]:
X_encoded = ct.fit_transform(X_ohe)
X_encoded

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [43]:
ohe_model = LinearRegression()
ohe_model.fit(X_encoded, y)

LinearRegression()

In [46]:
ohe_model.coef_

array([ 30000.,  27500.,  12500.,  47500.,  57500.,  65000., 125000.,
       172500., -32500., -12500.])

In [48]:
ohe_model.score(X_encoded, y)

<class 'ValueError'>: X has 3 features, but LinearRegression is expecting 10 features as input.